export const UserTypes = {
    GET_USER_CONTRACTS: 'GET_USER_CONTRACTS',
    GET_USERS: 'GET_USERS',
    GET_MY_AGREEMENTS: 'GET_MY_AGREEMENTS',
    GET_SIGN_AGREEMENTS: 'GET_SIGN_AGREEMENTS',
    GET_AGREEMENT: 'GET_AGREEMENT',
} 