export const UserTypes = {
    GET_USER_CONTRACTS_REQUEST: 'GET_USER_CONTRACTS_REQUEST', 
    GET_USER_CONTRACTS_SUCCESS: 'GET_USER_CONTRACTS_SUCCESS', 
    GET_USER_CONTRACTS_FAILURE: 'GET_USER_CONTRACTS_FAILURE',

    GET_USERS_REQUEST: 'GET_USERS_REQUEST', 
    GET_USERS_SUCCESS: 'GET_USERS_SUCCESS', 
    GET_USERS_FAILURE: 'GET_USERS_FAILURE',
} 