export const UserTypes = {
    GET_USERS: 'GET_USERS',
    GET_MY_AGREEMENTS: 'GET_MY_AGREEMENTS',
    GET_SIGN_AGREEMENTS: 'GET_SIGN_AGREEMENTS',
    GET_AGREEMENT: 'GET_AGREEMENT',
    CREATE_AGREEMENT: 'CREATE_AGREEMENT',
    CHANGE_STATUS: 'CHANGE_STATUS',
} 